# Generated by Django 5.0.4 on 2024-05-08 07:30

import chat.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[(chat.models.MessageStatus['SENT'], 'sent'), (chat.models.MessageStatus['RECEIVED'], 'received'), (chat.models.MessageStatus['ERROR'], 'error')], default=chat.models.MessageStatus['SENT'], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='time_first_token_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
