# Generated by Django 5.0.4 on 2024-04-12 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='messageTimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 11, 20, 3, 17, 559060)),
        ),
    ]
