# Generated by Django 5.0.4 on 2024-05-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_messagetimestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
